services:
  hitung-kilat:
    image: "${DOCKER_REGISTRY:-docker-hub.solusi-k8s.com}/${DOCKER_USER:-myindo}/${DOCKER_IMAGE:-hitung-kilat-web}:${DOCKER_VERSION:-v1.0.1}"
    container_name: hitung-kilat-local
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - hitung-kilat-loc-net

networks:
  hitung-kilat-loc-net:
    name: hitung-kilat-loc-net
    driver: bridge
