import { LevelConfigV2 } from '../types/level';

export const LEVEL_MANIFEST_72: LevelConfigV2[] = [
  // ==========================================
  // TIER 1: Pemula (Lv 01–12)
  // ==========================================
  {
    id: 'T1-ADD-01',
    order: 1,
    tier: 1,
    title: 'Penjumlahan 1–10',
    description: 'Tambah satuan',
    generatorKey: 'addition',
    rules: { kind: 'addition', minA: 1, maxA: 10, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 1,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: [],
    primarySkillId: 'addition.single_digit',
    skillTags: ['addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-ADD-02',
    order: 2,
    tier: 1,
    title: 'Penjumlahan 1–20',
    description: 'Tambah sampai 20',
    generatorKey: 'addition',
    rules: { kind: 'addition', minA: 1, maxA: 20, minB: 1, maxB: 20 },
    answerKind: 'integer',
    difficulty: 1,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-ADD-01'],
    primarySkillId: 'addition.within_20',
    skillTags: ['addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-SUB-01',
    order: 3,
    tier: 1,
    title: 'Pengurangan 1–15',
    description: 'Minus dasar tanpa negatif',
    generatorKey: 'subtraction',
    rules: { kind: 'subtraction', minA: 1, maxA: 15, minB: 1, maxB: 15, allowNegative: false },
    answerKind: 'integer',
    difficulty: 1,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-ADD-02'],
    primarySkillId: 'subtraction.single_digit',
    skillTags: ['subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-SUB-02',
    order: 4,
    tier: 1,
    title: 'Pengurangan 1–20',
    description: 'Minus lebih lebar',
    generatorKey: 'subtraction',
    rules: { kind: 'subtraction', minA: 1, maxA: 20, minB: 1, maxB: 20, allowNegative: false },
    answerKind: 'integer',
    difficulty: 1,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-SUB-01'],
    primarySkillId: 'subtraction.within_20',
    skillTags: ['subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-CHAIN-01',
    order: 5,
    tier: 1,
    title: 'Duo Tambah',
    description: 'Tiga operand tambah',
    generatorKey: 'chain',
    rules: { kind: 'chain', operators: ['+'], termsCount: 3, minOperand: 1, maxOperand: 10, allowIntermediateNegative: false },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-SUB-02'],
    primarySkillId: 'arithmetic.chain',
    skillTags: ['addition', 'chain'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-CHAIN-02',
    order: 6,
    tier: 1,
    title: 'Duo Kurang',
    description: 'Pengurangan berantai',
    generatorKey: 'chain',
    rules: { kind: 'chain', operators: ['-'], termsCount: 3, minOperand: 1, maxOperand: 20, allowIntermediateNegative: false },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-CHAIN-01'],
    primarySkillId: 'arithmetic.chain',
    skillTags: ['subtraction', 'chain'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-MIX-01',
    order: 7,
    tier: 1,
    title: 'Duo Tambah Kurang',
    description: '+ dan − berantai',
    generatorKey: 'chain',
    rules: { kind: 'chain', operators: ['+', '-'], termsCount: 3, minOperand: 1, maxOperand: 15, allowIntermediateNegative: false },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-CHAIN-02'],
    primarySkillId: 'arithmetic.chain',
    skillTags: ['addition', 'subtraction', 'chain'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-COMP-01',
    order: 8,
    tier: 1,
    title: 'Pasangan ke 10',
    description: 'Number complement',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '+', missingPosition: 'second', minA: 1, maxA: 9, minB: 1, maxB: 9 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-MIX-01'],
    primarySkillId: 'missing_operand.complement_10',
    skillTags: ['missing_operand', 'addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-COMP-02',
    order: 9,
    tier: 1,
    title: 'Pasangan ke 20',
    description: 'Number complement',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '+', missingPosition: 'first', minA: 1, maxA: 19, minB: 1, maxB: 19 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-COMP-01'],
    primarySkillId: 'missing_operand.complement_20',
    skillTags: ['missing_operand', 'addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-MISS-01',
    order: 10,
    tier: 1,
    title: 'Cari Angka Hilang +',
    description: 'Inverse addition',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '+', missingPosition: 'random', minA: 1, maxA: 20, minB: 1, maxB: 20 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-COMP-02'],
    primarySkillId: 'missing_operand.add_inverse',
    skillTags: ['missing_operand', 'addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-MISS-02',
    order: 11,
    tier: 1,
    title: 'Cari Angka Hilang −',
    description: 'Inverse subtraction',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '-', missingPosition: 'random', minA: 1, maxA: 20, minB: 1, maxB: 20 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 10,
    targetTimeSec: 30,
    timeLimitSec: 45,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-MISS-01'],
    primarySkillId: 'missing_operand.sub_inverse',
    skillTags: ['missing_operand', 'subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T1-BOSS',
    order: 12,
    tier: 1,
    title: 'Boss Pemula',
    description: 'Campuran T1',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'addition', minA: 1, maxA: 20, minB: 1, maxB: 20 },
        { kind: 'subtraction', minA: 1, maxA: 20, minB: 1, maxB: 20, allowNegative: false },
        { kind: 'chain', operators: ['+', '-'], termsCount: 3, minOperand: 1, maxOperand: 15, allowIntermediateNegative: false },
        { kind: 'missing_operand', operation: '+', missingPosition: 'random', minA: 1, maxA: 15, minB: 1, maxB: 15 },
        { kind: 'missing_operand', operation: '-', missingPosition: 'random', minA: 1, maxA: 15, minB: 1, maxB: 15 },
      ],
    },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 15,
    targetTimeSec: 36,
    timeLimitSec: 45,
    boss: true,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-MISS-02'],
    primarySkillId: 'tier_boss.t1',
    skillTags: ['boss', 'addition', 'subtraction', 'chain', 'missing_operand'],
    contentVersion: '2.0.0',
  },

  // ==========================================
  // TIER 2: Menengah (Lv 13–24)
  // ==========================================
  {
    id: 'T2-MUL-02',
    order: 13,
    tier: 2,
    title: 'Perkalian ×2',
    description: 'Tabel 2',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 2, minA: 2, maxA: 2, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T1-BOSS'],
    primarySkillId: 'multiplication.x2',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-03',
    order: 14,
    tier: 2,
    title: 'Perkalian ×3',
    description: 'Tabel 3',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 3, minA: 3, maxA: 3, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-02'],
    primarySkillId: 'multiplication.x3',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-04',
    order: 15,
    tier: 2,
    title: 'Perkalian ×4',
    description: 'Tabel 4',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 4, minA: 4, maxA: 4, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-03'],
    primarySkillId: 'multiplication.x4',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-05',
    order: 16,
    tier: 2,
    title: 'Perkalian ×5',
    description: 'Tabel 5',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 5, minA: 5, maxA: 5, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-04'],
    primarySkillId: 'multiplication.x5',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-06',
    order: 17,
    tier: 2,
    title: 'Perkalian ×6',
    description: 'Tabel 6',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 6, minA: 6, maxA: 6, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-05'],
    primarySkillId: 'multiplication.x6',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-07',
    order: 18,
    tier: 2,
    title: 'Perkalian ×7',
    description: 'Tabel 7',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 7, minA: 7, maxA: 7, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-06'],
    primarySkillId: 'multiplication.x7',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-08',
    order: 19,
    tier: 2,
    title: 'Perkalian ×8',
    description: 'Tabel 8',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 8, minA: 8, maxA: 8, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-07'],
    primarySkillId: 'multiplication.x8',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MUL-09',
    order: 20,
    tier: 2,
    title: 'Perkalian ×9',
    description: 'Tabel 9',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 9, minA: 9, maxA: 9, minB: 1, maxB: 10 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-08'],
    primarySkillId: 'multiplication.x9',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-DIV-01',
    order: 21,
    tier: 2,
    title: 'Pembagian Dasar',
    description: 'Divisor 2,3,5',
    generatorKey: 'division',
    rules: { kind: 'division', minDivisor: 2, maxDivisor: 5, minQuotient: 1, maxQuotient: 10, requireInteger: true },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MUL-09'],
    primarySkillId: 'division.basic',
    skillTags: ['division'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-DIV-02',
    order: 22,
    tier: 2,
    title: 'Pembagian Penuh',
    description: 'Divisor 4–9',
    generatorKey: 'division',
    rules: { kind: 'division', minDivisor: 4, maxDivisor: 9, minQuotient: 1, maxQuotient: 10, requireInteger: true },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-DIV-01'],
    primarySkillId: 'division.full',
    skillTags: ['division'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-MISS-01',
    order: 23,
    tier: 2,
    title: 'Misteri Pengali',
    description: 'Missing factor',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '×', missingPosition: 'random', minA: 2, maxA: 9, minB: 2, maxB: 9 },
    answerKind: 'integer',
    difficulty: 2,
    questionCount: 12,
    targetTimeSec: 36,
    timeLimitSec: 50,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-DIV-02'],
    primarySkillId: 'missing_operand.mul_inverse',
    skillTags: ['missing_operand', 'multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T2-BOSS',
    order: 24,
    tier: 2,
    title: 'Boss Kali Bagi',
    description: 'Semua ×/÷',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'multiplication', minA: 2, maxA: 9, minB: 2, maxB: 9 },
        { kind: 'division', minDivisor: 2, maxDivisor: 9, minQuotient: 2, maxQuotient: 9, requireInteger: true },
        { kind: 'missing_operand', operation: '×', missingPosition: 'random', minA: 2, maxA: 9, minB: 2, maxB: 9 },
        { kind: 'missing_operand', operation: '÷', missingPosition: 'random', minA: 2, maxA: 9, minB: 2, maxB: 9 },
      ],
    },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 18,
    targetTimeSec: 40,
    timeLimitSec: 50,
    boss: true,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-MISS-01'],
    primarySkillId: 'tier_boss.t2',
    skillTags: ['boss', 'multiplication', 'division'],
    contentVersion: '2.0.0',
  },

  // ==========================================
  // TIER 3: Terampil (Lv 25–36)
  // ==========================================
  {
    id: 'T3-ADD-01',
    order: 25,
    tier: 3,
    title: 'Tambah Puluhan',
    description: 'Dua digit tanpa fokus carry',
    generatorKey: 'addition',
    rules: { kind: 'addition', minA: 10, maxA: 50, minB: 10, maxB: 40 },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T2-BOSS'],
    primarySkillId: 'addition.two_digit',
    skillTags: ['addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-ADD-02',
    order: 26,
    tier: 3,
    title: 'Tambah dengan Carry',
    description: 'Carry satuan',
    generatorKey: 'addition',
    rules: { kind: 'addition', minA: 25, maxA: 99, minB: 15, maxB: 99 },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-ADD-01'],
    primarySkillId: 'addition.carry',
    skillTags: ['addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-SUB-01',
    order: 27,
    tier: 3,
    title: 'Kurang Puluhan',
    description: 'Dua digit mudah',
    generatorKey: 'subtraction',
    rules: { kind: 'subtraction', minA: 20, maxA: 99, minB: 10, maxB: 50, allowNegative: false },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-ADD-02'],
    primarySkillId: 'subtraction.two_digit',
    skillTags: ['subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-SUB-02',
    order: 28,
    tier: 3,
    title: 'Kurang dengan Borrow',
    description: 'Borrow',
    generatorKey: 'subtraction',
    rules: { kind: 'subtraction', minA: 30, maxA: 99, minB: 15, maxB: 89, allowNegative: false },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-SUB-01'],
    primarySkillId: 'subtraction.borrow',
    skillTags: ['subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-ADD-03',
    order: 29,
    tier: 3,
    title: 'Tambah Ratusan',
    description: 'Mental addition ratusan',
    generatorKey: 'addition',
    rules: { kind: 'addition', minA: 100, maxA: 500, minB: 20, maxB: 300 },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-SUB-02'],
    primarySkillId: 'addition.hundreds',
    skillTags: ['addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-SUB-03',
    order: 30,
    tier: 3,
    title: 'Kurang Ratusan',
    description: 'Mental subtraction ratusan',
    generatorKey: 'subtraction',
    rules: { kind: 'subtraction', minA: 100, maxA: 500, minB: 20, maxB: 300, allowNegative: false },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-ADD-03'],
    primarySkillId: 'subtraction.hundreds',
    skillTags: ['subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-MUL-10',
    order: 31,
    tier: 3,
    title: 'Kali 10 & 100',
    description: 'Place value',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', fixedOperand: 10, minA: 10, maxA: 10, minB: 11, maxB: 99 },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-SUB-03'],
    primarySkillId: 'multiplication.place_value',
    skillTags: ['multiplication', 'tens'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-DIV-10',
    order: 32,
    tier: 3,
    title: 'Bagi 10 & 100',
    description: 'Place value',
    generatorKey: 'division',
    rules: { kind: 'division', minDivisor: 10, maxDivisor: 10, minQuotient: 10, maxQuotient: 99, requireInteger: true },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-MUL-10'],
    primarySkillId: 'division.place_value',
    skillTags: ['division', 'tens'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-MUL-TENS',
    order: 33,
    tier: 3,
    title: 'Puluhan × Satuan',
    description: 'Tens multiplication',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', minA: 10, maxA: 90, minB: 2, maxB: 9 },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-DIV-10'],
    primarySkillId: 'multiplication.tens',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-DIV-TENS',
    order: 34,
    tier: 3,
    title: 'Puluhan ÷ Satuan',
    description: 'Clean division',
    generatorKey: 'division',
    rules: { kind: 'division', minDivisor: 2, maxDivisor: 9, minQuotient: 10, maxQuotient: 90, requireInteger: true },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-MUL-TENS'],
    primarySkillId: 'division.tens',
    skillTags: ['division'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-MIX-01',
    order: 35,
    tier: 3,
    title: '4 Operasi Dasar',
    description: '+ − × ÷ random',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'addition', minA: 10, maxA: 99, minB: 10, maxB: 99 },
        { kind: 'subtraction', minA: 10, maxA: 99, minB: 10, maxB: 99, allowNegative: false },
        { kind: 'multiplication', minA: 2, maxA: 9, minB: 2, maxB: 9 },
        { kind: 'division', minDivisor: 2, maxDivisor: 9, minQuotient: 2, maxQuotient: 9, requireInteger: true },
      ],
    },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 12,
    targetTimeSec: 40,
    timeLimitSec: 55,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-DIV-TENS'],
    primarySkillId: 'arithmetic.four_operations',
    skillTags: ['addition', 'subtraction', 'multiplication', 'division'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T3-BOSS',
    order: 36,
    tier: 3,
    title: 'Boss Terampil',
    description: 'Campuran T1–T3',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'addition', minA: 20, maxA: 99, minB: 20, maxB: 99 },
        { kind: 'subtraction', minA: 20, maxA: 99, minB: 10, maxB: 89, allowNegative: false },
        { kind: 'multiplication', minA: 2, maxA: 12, minB: 2, maxB: 12 },
        { kind: 'division', minDivisor: 2, maxDivisor: 12, minQuotient: 2, maxQuotient: 12, requireInteger: true },
        { kind: 'chain', operators: ['+', '-'], termsCount: 3, minOperand: 5, maxOperand: 30, allowIntermediateNegative: false },
      ],
    },
    answerKind: 'integer',
    difficulty: 3,
    questionCount: 18,
    targetTimeSec: 48,
    timeLimitSec: 60,
    boss: true,
    passingAccuracy: 0.75,
    prerequisiteIds: ['T3-MIX-01'],
    primarySkillId: 'tier_boss.t3',
    skillTags: ['boss', 'arithmetic', 'multi_operation'],
    contentVersion: '2.0.0',
  },

  // ==========================================
  // TIER 4: Mahir (Lv 37–48)
  // ==========================================
  {
    id: 'T4-CHAIN-03',
    order: 37,
    tier: 4,
    title: 'Tiga Angka Beruntun',
    description: 'Tiga operand',
    generatorKey: 'chain',
    rules: { kind: 'chain', operators: ['+', '-'], termsCount: 3, minOperand: 5, maxOperand: 35, allowIntermediateNegative: false },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T3-BOSS'],
    primarySkillId: 'multi_operation.three_terms',
    skillTags: ['chain', 'arithmetic'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-CHAIN-04',
    order: 38,
    tier: 4,
    title: 'Empat Angka Beruntun',
    description: 'Empat operand',
    generatorKey: 'chain',
    rules: { kind: 'chain', operators: ['+', '-'], termsCount: 4, minOperand: 2, maxOperand: 25, allowIntermediateNegative: false },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-CHAIN-03'],
    primarySkillId: 'multi_operation.four_terms',
    skillTags: ['chain', 'arithmetic'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-MIX-MA',
    order: 39,
    tier: 4,
    title: 'Kali + Tambah',
    description: '× dan +',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_times_b_plus_c', minOperand: 2, maxOperand: 12 },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-CHAIN-04'],
    primarySkillId: 'bodmas.mul_add',
    skillTags: ['bodmas', 'multiplication', 'addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-MIX-MS',
    order: 40,
    tier: 4,
    title: 'Kali + Kurang',
    description: '× dan −',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_times_b_plus_c', minOperand: 2, maxOperand: 12 },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-MIX-MA'],
    primarySkillId: 'bodmas.mul_sub',
    skillTags: ['bodmas', 'multiplication', 'subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-MIX-DA',
    order: 41,
    tier: 4,
    title: 'Bagi + Tambah',
    description: '÷ dan +',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_minus_b_div_c', minOperand: 2, maxOperand: 12, requireCleanDivision: true },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-MIX-MS'],
    primarySkillId: 'bodmas.div_add',
    skillTags: ['bodmas', 'division', 'addition'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-MIX-DS',
    order: 42,
    tier: 4,
    title: 'Bagi + Kurang',
    description: '÷ dan −',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_minus_b_div_c', minOperand: 2, maxOperand: 12, requireCleanDivision: true },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-MIX-DA'],
    primarySkillId: 'bodmas.div_sub',
    skillTags: ['bodmas', 'division', 'subtraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-BODMAS-01',
    order: 43,
    tier: 4,
    title: 'Prioritas Perkalian',
    description: 'BODMAS dasar',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_plus_b_times_c', minOperand: 2, maxOperand: 10 },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-MIX-DS'],
    primarySkillId: 'bodmas.mul_priority',
    skillTags: ['bodmas', 'precedence'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-BODMAS-02',
    order: 44,
    tier: 4,
    title: 'Prioritas Pembagian',
    description: 'BODMAS dasar',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'a_minus_b_div_c', minOperand: 2, maxOperand: 10, requireCleanDivision: true },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-BODMAS-01'],
    primarySkillId: 'bodmas.div_priority',
    skillTags: ['bodmas', 'precedence'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-PAREN-01',
    order: 45,
    tier: 4,
    title: 'Operasi Kurung',
    description: 'Parentheses',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'paren_add_div_c', minOperand: 2, maxOperand: 12, requireCleanDivision: true },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-BODMAS-02'],
    primarySkillId: 'bodmas.parentheses',
    skillTags: ['bodmas', 'parentheses'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-PAREN-02',
    order: 46,
    tier: 4,
    title: 'Kurung + Perkalian',
    description: 'Parentheses mixed',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'paren_sub_mul_c', minOperand: 2, maxOperand: 12 },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-PAREN-01'],
    primarySkillId: 'bodmas.parentheses',
    skillTags: ['bodmas', 'parentheses'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-BODMAS-03',
    order: 47,
    tier: 4,
    title: 'BODMAS Mahir',
    description: 'Multi precedence',
    generatorKey: 'bodmas',
    rules: { kind: 'bodmas', template: 'paren_nested_bodmas', minOperand: 2, maxOperand: 10 },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 12,
    targetTimeSec: 45,
    timeLimitSec: 60,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-PAREN-02'],
    primarySkillId: 'bodmas.advanced',
    skillTags: ['bodmas', 'nested'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T4-BOSS',
    order: 48,
    tier: 4,
    title: 'Boss BODMAS',
    description: 'Semua T4',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'chain', operators: ['+', '-'], termsCount: 4, minOperand: 2, maxOperand: 25, allowIntermediateNegative: false },
        { kind: 'bodmas', template: 'a_plus_b_times_c', minOperand: 2, maxOperand: 10 },
        { kind: 'bodmas', template: 'a_minus_b_div_c', minOperand: 2, maxOperand: 10, requireCleanDivision: true },
        { kind: 'bodmas', template: 'paren_add_div_c', minOperand: 2, maxOperand: 12, requireCleanDivision: true },
        { kind: 'bodmas', template: 'paren_sub_mul_c', minOperand: 2, maxOperand: 12 },
        { kind: 'bodmas', template: 'paren_nested_bodmas', minOperand: 2, maxOperand: 10 },
      ],
    },
    answerKind: 'integer',
    difficulty: 4,
    questionCount: 15,
    targetTimeSec: 48,
    timeLimitSec: 60,
    boss: true,
    passingAccuracy: 0.75,
    prerequisiteIds: ['T4-BODMAS-03'],
    primarySkillId: 'tier_boss.t4',
    skillTags: ['boss', 'bodmas', 'parentheses'],
    contentVersion: '2.0.0',
  },

  // ==========================================
  // TIER 5: Master (Lv 49–60)
  // ==========================================
  {
    id: 'T5-NEG-01',
    order: 49,
    tier: 5,
    title: 'Bilangan Negatif',
    description: 'Hasil negatif',
    generatorKey: 'signed',
    rules: { kind: 'signed', operation: '-', minOperand: 1, maxOperand: 50, allowZeroOperand: false },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T4-BOSS'],
    primarySkillId: 'arithmetic.signed',
    skillTags: ['signed', 'subtraction', 'negative'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-NEG-02',
    order: 50,
    tier: 5,
    title: 'Negatif + Positif',
    description: 'Signed number',
    generatorKey: 'signed',
    rules: { kind: 'signed', operation: '+', minOperand: -30, maxOperand: 30, allowZeroOperand: false },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-NEG-01'],
    primarySkillId: 'arithmetic.signed',
    skillTags: ['signed', 'addition', 'negative'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-NEG-03',
    order: 51,
    tier: 5,
    title: 'Negatif − Negatif',
    description: 'Signed subtraction',
    generatorKey: 'signed',
    rules: { kind: 'signed', operation: '-', minOperand: -30, maxOperand: 30, allowZeroOperand: false },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-NEG-02'],
    primarySkillId: 'arithmetic.signed',
    skillTags: ['signed', 'subtraction', 'negative'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-NEG-MUL',
    order: 52,
    tier: 5,
    title: 'Kali Negatif',
    description: 'Sign multiplication',
    generatorKey: 'signed',
    rules: { kind: 'signed', operation: '×', minOperand: -12, maxOperand: 12, allowZeroOperand: false },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-NEG-03'],
    primarySkillId: 'arithmetic.signed',
    skillTags: ['signed', 'multiplication', 'negative'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-NEG-DIV',
    order: 53,
    tier: 5,
    title: 'Bagi Negatif',
    description: 'Sign division',
    generatorKey: 'signed',
    rules: { kind: 'signed', operation: '÷', minOperand: -12, maxOperand: 12, allowZeroOperand: false },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-NEG-MUL'],
    primarySkillId: 'arithmetic.signed',
    skillTags: ['signed', 'division', 'negative'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-MUL-11-14',
    order: 54,
    tier: 5,
    title: 'Perkalian 11–14',
    description: 'Mental multiplication',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', minA: 11, maxA: 14, minB: 2, maxB: 12 },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-NEG-DIV'],
    primarySkillId: 'multiplication.intermediate',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-MUL-15-19',
    order: 55,
    tier: 5,
    title: 'Perkalian 15–19',
    description: 'Mental multiplication',
    generatorKey: 'multiplication',
    rules: { kind: 'multiplication', minA: 15, maxA: 19, minB: 2, maxB: 12 },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-MUL-11-14'],
    primarySkillId: 'multiplication.intermediate',
    skillTags: ['multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-MISS-02',
    order: 56,
    tier: 5,
    title: 'Misteri Operand',
    description: 'Inverse operation',
    generatorKey: 'missing_operand',
    rules: { kind: 'missing_operand', operation: '×', missingPosition: 'second', minA: 6, maxA: 15, minB: 3, maxB: 15 },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-MUL-15-19'],
    primarySkillId: 'missing_operand.advanced',
    skillTags: ['missing_operand', 'multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-ALG-01',
    order: 57,
    tier: 5,
    title: 'Aljabar 1 Langkah',
    description: 'Linear basic',
    generatorKey: 'algebra',
    rules: { kind: 'algebra', template: 'one_step_add', variableName: 'x', minSolution: 1, maxSolution: 25, minCoefficient: 1, maxCoefficient: 1 },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-MISS-02'],
    primarySkillId: 'algebra.linear',
    skillTags: ['algebra', 'linear'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-ALG-02',
    order: 58,
    tier: 5,
    title: 'Aljabar 2 Langkah',
    description: 'Linear two-step',
    generatorKey: 'algebra',
    rules: { kind: 'algebra', template: 'two_step_linear', variableName: 'x', minSolution: 1, maxSolution: 15, minCoefficient: 2, maxCoefficient: 6 },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-ALG-01'],
    primarySkillId: 'algebra.linear',
    skillTags: ['algebra', 'linear'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-BLITZ',
    order: 59,
    tier: 5,
    title: 'Master Blitz',
    description: 'Mixed high speed',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'signed', operation: '+', minOperand: -25, maxOperand: 25, allowZeroOperand: false },
        { kind: 'signed', operation: '-', minOperand: -25, maxOperand: 25, allowZeroOperand: false },
        { kind: 'multiplication', minA: 11, maxA: 19, minB: 2, maxB: 9 },
        { kind: 'algebra', template: 'one_step_add', variableName: 'x', minSolution: 1, maxSolution: 20, minCoefficient: 1, maxCoefficient: 1 },
        { kind: 'algebra', template: 'two_step_linear', variableName: 'x', minSolution: 1, maxSolution: 10, minCoefficient: 2, maxCoefficient: 5 },
      ],
    },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 12,
    targetTimeSec: 50,
    timeLimitSec: 65,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-ALG-02'],
    primarySkillId: 'mixed.blitz',
    skillTags: ['blitz', 'signed', 'algebra', 'multiplication'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T5-BOSS',
    order: 60,
    tier: 5,
    title: 'Boss Master',
    description: 'Semua T1–T5',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'signed', operation: '+', minOperand: -30, maxOperand: 30, allowZeroOperand: false },
        { kind: 'signed', operation: '×', minOperand: -12, maxOperand: 12, allowZeroOperand: false },
        { kind: 'algebra', template: 'two_step_linear', variableName: 'x', minSolution: 1, maxSolution: 12, minCoefficient: 2, maxCoefficient: 5 },
        { kind: 'bodmas', template: 'paren_nested_bodmas', minOperand: 2, maxOperand: 10 },
        { kind: 'chain', operators: ['+', '-'], termsCount: 4, minOperand: 2, maxOperand: 20, allowIntermediateNegative: false },
        { kind: 'multiplication', minA: 12, maxA: 19, minB: 3, maxB: 9 },
      ],
    },
    answerKind: 'integer',
    difficulty: 5,
    questionCount: 20,
    targetTimeSec: 60,
    timeLimitSec: 75,
    boss: true,
    passingAccuracy: 0.8,
    prerequisiteIds: ['T5-BLITZ'],
    primarySkillId: 'tier_boss.t5',
    skillTags: ['boss', 'master', 'algebra', 'signed', 'bodmas'],
    contentVersion: '2.0.0',
  },

  // ==========================================
  // TIER 6: Legenda (Lv 61–72)
  // ==========================================
  {
    id: 'T6-SQUARE-01',
    order: 61,
    tier: 6,
    title: 'Kuadrat 1²–10²',
    description: 'Square recall',
    generatorKey: 'power_root',
    rules: { kind: 'power_root', mode: 'square', minBase: 1, maxBase: 10 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T5-BOSS'],
    primarySkillId: 'arithmetic.square',
    skillTags: ['square', 'power'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-SQUARE-02',
    order: 62,
    tier: 6,
    title: 'Kuadrat 11²–15²',
    description: 'Square recall',
    generatorKey: 'power_root',
    rules: { kind: 'power_root', mode: 'square', minBase: 11, maxBase: 15 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-SQUARE-01'],
    primarySkillId: 'arithmetic.square',
    skillTags: ['square', 'power'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-SQUARE-03',
    order: 63,
    tier: 6,
    title: 'Kuadrat 16²–25²',
    description: 'Square recall',
    generatorKey: 'power_root',
    rules: { kind: 'power_root', mode: 'square', minBase: 16, maxBase: 25 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-SQUARE-02'],
    primarySkillId: 'arithmetic.square',
    skillTags: ['square', 'power'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-ROOT-01',
    order: 64,
    tier: 6,
    title: 'Akar Kuadrat',
    description: 'Perfect square roots',
    generatorKey: 'power_root',
    rules: { kind: 'power_root', mode: 'square_root', minBase: 2, maxBase: 25 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-SQUARE-03'],
    primarySkillId: 'arithmetic.square_root',
    skillTags: ['root', 'square_root'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-PCT-01',
    order: 65,
    tier: 6,
    title: 'Persentase Dasar',
    description: '10%, 20%, 25%, 50%',
    generatorKey: 'fraction_percentage',
    rules: { kind: 'fraction_percentage', variant: 'mental_percentage', minBase: 20, maxBase: 400 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-ROOT-01'],
    primarySkillId: 'percentage.mental',
    skillTags: ['percentage'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-PCT-02',
    order: 66,
    tier: 6,
    title: 'Persentase Kilat',
    description: 'Non-trivial percent',
    generatorKey: 'fraction_percentage',
    rules: { kind: 'fraction_percentage', variant: 'mental_percentage', minBase: 40, maxBase: 600 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-PCT-01'],
    primarySkillId: 'percentage.mental',
    skillTags: ['percentage'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-FRAC-01',
    order: 67,
    tier: 6,
    title: 'Pecahan Mental',
    description: 'Pecahan sederhana',
    generatorKey: 'fraction_percentage',
    rules: { kind: 'fraction_percentage', variant: 'fraction_add', minBase: 2, maxBase: 10 },
    answerKind: 'rational',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-PCT-02'],
    primarySkillId: 'fraction.addition',
    skillTags: ['fraction'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-RATIO-01',
    order: 68,
    tier: 6,
    title: 'Rasio Kilat',
    description: 'Equivalent ratio',
    generatorKey: 'fraction_percentage',
    rules: { kind: 'fraction_percentage', variant: 'ratio_equality', minBase: 2, maxBase: 12 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-FRAC-01'],
    primarySkillId: 'ratio.equivalent',
    skillTags: ['ratio'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-ALG-03',
    order: 69,
    tier: 6,
    title: 'Aljabar Bersarang',
    description: 'Parenthesized linear',
    generatorKey: 'algebra',
    rules: { kind: 'algebra', template: 'nested_linear', variableName: 'x', minSolution: 1, maxSolution: 10, minCoefficient: 2, maxCoefficient: 5 },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-RATIO-01'],
    primarySkillId: 'algebra.linear',
    skillTags: ['algebra', 'nested'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-MULTI',
    order: 70,
    tier: 6,
    title: 'Multi-Operasi Kilat',
    description: 'Advanced BODMAS',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'bodmas', template: 'paren_nested_bodmas', minOperand: 2, maxOperand: 12 },
        { kind: 'chain', operators: ['+', '-'], termsCount: 4, minOperand: 3, maxOperand: 30, allowIntermediateNegative: false },
        { kind: 'power_root', mode: 'square', minBase: 4, maxBase: 15 },
        { kind: 'fraction_percentage', variant: 'ratio_equality', minBase: 2, maxBase: 10 },
      ],
    },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-ALG-03'],
    primarySkillId: 'multi_operation.advanced',
    skillTags: ['multi_operation', 'bodmas', 'chain'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-BLITZ',
    order: 71,
    tier: 6,
    title: 'Legendary Blitz',
    description: 'Dynamic advanced mix',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'power_root', mode: 'square', minBase: 11, maxBase: 25 },
        { kind: 'power_root', mode: 'square_root', minBase: 5, maxBase: 25 },
        { kind: 'fraction_percentage', variant: 'mental_percentage', minBase: 20, maxBase: 500 },
        { kind: 'algebra', template: 'nested_linear', variableName: 'x', minSolution: 1, maxSolution: 10, minCoefficient: 2, maxCoefficient: 5 },
        { kind: 'signed', operation: '×', minOperand: -15, maxOperand: 15, allowZeroOperand: false },
      ],
    },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 12,
    targetTimeSec: 55,
    timeLimitSec: 70,
    boss: false,
    passingAccuracy: 0.7,
    prerequisiteIds: ['T6-MULTI'],
    primarySkillId: 'mixed.blitz',
    skillTags: ['blitz', 'legendary', 'mixed'],
    contentVersion: '2.0.0',
  },
  {
    id: 'T6-GRANDMASTER',
    order: 72,
    tier: 6,
    title: 'Ujian Akhir Grandmaster',
    description: 'Final comprehensive boss',
    generatorKey: 'mixed_blitz',
    rules: {
      kind: 'mixed_blitz',
      subRules: [
        { kind: 'addition', minA: 50, maxA: 500, minB: 50, maxB: 500 },
        { kind: 'subtraction', minA: 100, maxA: 500, minB: 20, maxB: 400, allowNegative: false },
        { kind: 'multiplication', minA: 11, maxA: 19, minB: 4, maxB: 12 },
        { kind: 'division', minDivisor: 4, maxDivisor: 15, minQuotient: 5, maxQuotient: 25, requireInteger: true },
        { kind: 'chain', operators: ['+', '-'], termsCount: 4, minOperand: 5, maxOperand: 40, allowIntermediateNegative: false },
        { kind: 'bodmas', template: 'paren_nested_bodmas', minOperand: 2, maxOperand: 12 },
        { kind: 'signed', operation: '×', minOperand: -12, maxOperand: 12, allowZeroOperand: false },
        { kind: 'algebra', template: 'nested_linear', variableName: 'x', minSolution: 1, maxSolution: 10, minCoefficient: 2, maxCoefficient: 5 },
        { kind: 'power_root', mode: 'square', minBase: 12, maxBase: 25 },
        { kind: 'power_root', mode: 'square_root', minBase: 5, maxBase: 25 },
        { kind: 'fraction_percentage', variant: 'mental_percentage', minBase: 20, maxBase: 400 },
        { kind: 'fraction_percentage', variant: 'ratio_equality', minBase: 2, maxBase: 10 },
      ],
    },
    answerKind: 'integer',
    difficulty: 6,
    questionCount: 25,
    targetTimeSec: 72,
    timeLimitSec: 90,
    boss: true,
    passingAccuracy: 0.85,
    prerequisiteIds: ['T6-BLITZ'],
    primarySkillId: 'tier_boss.t6_grandmaster',
    skillTags: ['boss', 'grandmaster', 'all_skills'],
    contentVersion: '2.0.0',
  },
];
